### ISSUE TITLE
Speech voices probably bug

### ISSUE THREAD

**Issue by MikhailCarpov** [abrahamjuliot/creepjs#103]
The first opening often fails the test. The second opening the test works correctly.
![test1 1](https://user-images.githubusercontent.com/66925827/103481779-18e2bd00-4dee-11eb-844a-5e0e37205400.jpg)
![test1 2](https://user-images.githubusercontent.com/66925827/103481775-17b19000-4dee-11eb-8834-2f24b508325b.jpg)
![test2](https://user-images.githubusercontent.com/66925827/103481776-18e2bd00-4dee-11eb-9647-729d4ce4f986.jpg)

**Comment by abrahamjuliot** [comment]
I believe this is a bug fixed in 9741d60. It's now live. Give it try. Let me know if it persists.

**Comment by MikhailCarpov** [comment]
The problem with the test is saved.
![photo_2021-01-07_02-15-12](https://user-images.githubusercontent.com/66925827/103832995-d4c31700-5090-11eb-8c75-ff421acf7847.jpg)
![photo_2021-01-07_02-16-01](https://user-images.githubusercontent.com/66925827/103832997-d55bad80-5090-11eb-9729-1d4fb0932b0b.jpg)

**Comment by abrahamjuliot** [comment]
Sounds good. Closing for now.
