### ISSUE TITLE
False positives for pixelDepth and colorDepth on macOS

### ISSUE THREAD

**Issue by Niek** [abrahamjuliot/creepjs#105]
On macOS Big Sur + Chrome 88:
```
1: screen: colorDepth (30) is not within set [0, 16, 24, 32]
2: screen: pixelDepth (30) is not within set [0, 16, 24, 32]
```

**Comment by abrahamjuliot** [comment]
Thanks for catching this. I removed the `colorDepth` and `pixelDepth` soundness tests since (in addition to missing `30`) they do not factor in cutting edge depths > 48 or older machines where color and pixel do not match.
