### ISSUE TITLE
Detect web extensions

### ISSUE THREAD

**Issue by abrahamjuliot** [abrahamjuliot/creepjs#106]
Detecting extensions in a chromium browser is rather candid. The `manifest.json` file can be viewed in a non-incognito window and under `web_accessible_resources`, the paths here are public, and then the list of public files can be obtained from the system folder.

For example, this will detect Grammarly
```js
fetch('chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/css/Grammarly.styles.css')
.then(() => console.log('extension found'))
.catch(error => console.log('extension not found'))
```

Chrome Profile Path is at chrome://version/

Steps to obtain resources:
- example: open `chrome-extension://chlffgpmiacpedhhbkiomidkjlcfhogd/manifest.json`
- resources are listed in `web_accessible_resources`

How to get webstore links
- example: `https://chrome.google.com/webstore/category/collection/wfh`
- `[...document.querySelectorAll('.webstore-test-wall-tile a')].map(x => x.href)`

Concept

```js
getChromeExtensions = async () => {
    const extensions = {
        'aapbdbdomjkkjkaonfhkkikfgjllcleb': { name: 'Google Translate', file: 'popup_css_compiled.css' },
        'fake': { name: 'fake', file: 'broken.css' },
        'kbfnbcaeplbcioakkpcpgfkobkghlhen': { name: 'Grammarly', file: 'src/css/Grammarly.styles.css' },
        'kgjfgplpablkjnlkjmjdecgdpfankdle': { name: 'Zoom Scheduler', file: 'images/icon.svg'}
    }
    const urls = Object.keys(extensions).map(key => `chrome-extension://${key}/${extensions[key].file}`)
    const idMatcher = /\/\/([^\/]+)/
    const getName = res => extensions[idMatcher.exec(res.url)[1]].name
    console.log(urls)
    const result = Promise.all(urls.map(url => fetch(url).then(getName).catch(e => {}))).then(res => res.filter(x => !!x))
    return result
}
await getChromeExtensions()
```

**Comment by abrahamjuliot** [comment]
Firefox addons can be targeted and identified through JS and CSS behavior detection, but (as far as I know) the limit with this method is extension behavior is not consistent across sites and the code is subject to change. But, with this method, it would still be easy to rate the probability of the extension being used based on known behavior.

**Comment by abrahamjuliot** [comment]
Popular:

Google Translate
Adobe Acrobat
Tampermonkey
Avast Online Security
Adblock Plus
Adblock
uBlock Origin
Pinterest Save Button
Cisco Webex
Grammarly for Chrome
Skype
Avast SafePrice
Honey

**Comment by abrahamjuliot** [comment]
Top categories: 

https://chrome.google.com/webstore/category/ext/7-productivity

**Comment by abrahamjuliot** [comment]
uBO filters (cosmetic)

```html
<div class="glx-teaser">glx-teaser</div>
<div class="inplayer-ad">inplayer-ad</div>
<div class="inplayer_banners">inplayer_banners</div>
<div class="in_stream_banner">in_stream_banner</div>
<div class="dbanner">dbanner</div>
<div class="preroll-blocker">preroll-blocker</div>
<div class="happy-inside-player">happy-inside-player</div>
<div>safe</div>
```

**Comment by Thorin-Oakenpants** [comment]
in Firefox what is shifted, or added, after `constructor` in iframe.contentWindow properties can be very telling

here is `AdBlocker Ultimate` (2nd highest number of users on Firefox)
```
"Array"
​"Element"
​"HTMLElement"
​"HTMLFrameElement"
​"HTMLIFrameElement"
​"HTMLObjectElement"
​"RTCPeerConnection"
​"String"
​"WeakSet"
​"decodeURI"
"decodeURIComponent"
​"encodeURI"
​"encodeURIComponent"
​"escape"
​"unescape"
```

**Comment by abrahamjuliot** [comment]
Nice. I might use that. I'm looking for a 2nd detection method to improve the current technique I'm working on in 8a8917d. Right now the section is focused on detecting resistance but it also detects extensions based on unique patterns in prototype lie details and relies on a stable set of APIs present with minimal extension settings.

**Comment by Thorin-Oakenpants** [comment]
> here is `AdBlocker Ultimate` (2nd highest number of users on Firefox)

NFI why it came up as No. 2, it's actually No. 7. `Adblock Plus` is No. 1 and has the same result

**Comment by abrahamjuliot** [comment]
Initial concept is live at https://abrahamjuliot.github.io/creepjs/tests/extensions.html
