### ISSUE TITLE
WebGL Parameters missing + How to call remotely without DOM patch?

### ISSUE THREAD

**Issue by earthlion** [abrahamjuliot/creepjs#111]
Hi I've seen there are quite a few WebGL1/2 parameters missing.

Would you be able to add them, so its complete?

Also how would you call the js file and retrieve fp/creep js objects from an external html and process it (without patching dom)?

Big thanks

**Comment by abrahamjuliot** [comment]
I've created 2 side issues to focus on this (#112 and #113). Feel free to chime in on these.

> WebGL1/2 parameters missing

Thank you for this request. I have started refactoring the [canvasWebgl](https://github.com/abrahamjuliot/creepjs/blob/master/modules/canvasWebgl.js) script to cover more/most parameters (based on Chrome and Firefox stable channels). However, there is a 2x performance increase which can be dramatic on slow machines, so I'm looking at ways to optimize it or reduce the params to those yielding the highest entropy.

> retrieve fp/creep js objects

I plan to compile and release a non-template script set with documentation, but you can begin testing with the Github pages `creep.js` and `creepworker.js` files in `/docs`. 

In `creep.js` delete everything after [the promise resolves](https://github.com/abrahamjuliot/creepjs/blob/7c41da78bdd208966ee54d321875a559991a8c5e/docs/creep.js#L4880) `fpHash` and `creepHash`.

```js
// deliver the goods
const [fpHash, creepHash] = await Promise.all([hashify(fp), hashify(creep)])
.catch(error => { 
	console.error(error.message)
})
```
