### ISSUE TITLE
rafactor webgl

### ISSUE THREAD

**Issue by abrahamjuliot** [abrahamjuliot/creepjs#112]
- [x] detect mismatching on mirrored parameters
- [x] simplify template output
- [x] display drawn image
- [x] search all available parameters in the prototype (per #111)

**Comment by earthlion** [comment]
WebGL Params I know of:

`"webGlParams":[{"name":"BLEND_EQUATION","code":32777,"ext":"webgl","value":32774},{"name":"BLEND_EQUATION_RGB","code":32777,"ext":"webgl","value":32774},{"name":"BLEND_EQUATION_ALPHA","code":34877,"ext":"webgl","value":32774},{"name":"BLEND_DST_RGB","code":32968,"ext":"webgl","value":0},{"name":"BLEND_SRC_RGB","code":32969,"ext":"webgl","value":1},{"name":"BLEND_DST_ALPHA","code":32970,"ext":"webgl","value":0},{"name":"BLEND_SRC_ALPHA","code":32971,"ext":"webgl","value":1},{"name":"BLEND_COLOR","code":32773,"ext":"webgl","value":[0,0,0,0]},{"name":"CULL_FACE","code":2884,"ext":"webgl","value":false},{"name":"BLEND","code":3042,"ext":"webgl","value":false},{"name":"DITHER","code":3024,"ext":"webgl","value":true},{"name":"STENCIL_TEST","code":2960,"ext":"webgl","value":false},{"name":"DEPTH_TEST","code":2929,"ext":"webgl","value":false},{"name":"SCISSOR_TEST","code":3089,"ext":"webgl","value":false},{"name":"POLYGON_OFFSET_FILL","code":32823,"ext":"webgl","value":false},{"name":"SAMPLE_ALPHA_TO_COVERAGE","code":32926,"ext":"webgl","value":false},{"name":"SAMPLE_COVERAGE","code":32928,"ext":"webgl","value":false},{"name":"LINE_WIDTH","code":2849,"ext":"webgl","value":1},{"name":"ALIASED_POINT_SIZE_RANGE","code":33901,"ext":"webgl","value":[1,1024]},{"name":"ALIASED_LINE_WIDTH_RANGE","code":33902,"ext":"webgl","value":[1,1]},{"name":"CULL_FACE_MODE","code":2885,"ext":"webgl","value":1029},{"name":"FRONT_FACE","code":2886,"ext":"webgl","value":2305},{"name":"DEPTH_RANGE","code":2928,"ext":"webgl","value":[0,1]},{"name":"DEPTH_WRITEMASK","code":2930,"ext":"webgl","value":true},{"name":"DEPTH_CLEAR_VALUE","code":2931,"ext":"webgl","value":1},{"name":"DEPTH_FUNC","code":2932,"ext":"webgl","value":513},{"name":"STENCIL_CLEAR_VALUE","code":2961,"ext":"webgl","value":0},{"name":"STENCIL_FUNC","code":2962,"ext":"webgl","value":519},{"name":"STENCIL_FAIL","code":2964,"ext":"webgl","value":7680},{"name":"STENCIL_PASS_DEPTH_FAIL","code":2965,"ext":"webgl","value":7680},{"name":"STENCIL_PASS_DEPTH_PASS","code":2966,"ext":"webgl","value":7680},{"name":"STENCIL_REF","code":2967,"ext":"webgl","value":0},{"name":"STENCIL_VALUE_MASK","code":2963,"ext":"webgl","value":2147483647},{"name":"STENCIL_WRITEMASK","code":2968,"ext":"webgl","value":2147483647},{"name":"STENCIL_BACK_FUNC","code":34816,"ext":"webgl","value":519},{"name":"STENCIL_BACK_FAIL","code":34817,"ext":"webgl","value":7680},{"name":"STENCIL_BACK_PASS_DEPTH_FAIL","code":34818,"ext":"webgl","value":7680},{"name":"STENCIL_BACK_PASS_DEPTH_PASS","code":34819,"ext":"webgl","value":7680},{"name":"STENCIL_BACK_REF","code":36003,"ext":"webgl","value":0},{"name":"STENCIL_BACK_VALUE_MASK","code":36004,"ext":"webgl","value":2147483647},{"name":"STENCIL_BACK_WRITEMASK","code":36005,"ext":"webgl","value":2147483647},{"name":"VIEWPORT","code":2978,"ext":"webgl","value":[0,0,300,150]},{"name":"SCISSOR_BOX","code":3088,"ext":"webgl","value":[0,0,300,150]},{"name":"COLOR_CLEAR_VALUE","code":3106,"ext":"webgl","value":[0,0,0,0]},{"name":"COLOR_WRITEMASK","code":3107,"ext":"webgl","value":[true,true,true,true]},{"name":"UNPACK_ALIGNMENT","code":3317,"ext":"webgl","value":4},{"name":"PACK_ALIGNMENT","code":3333,"ext":"webgl","value":4},{"name":"MAX_TEXTURE_SIZE","code":3379,"ext":"webgl","value":16384},{"name":"MAX_VIEWPORT_DIMS","code":3386,"ext":"webgl","value":[32767,32767]},{"name":"SUBPIXEL_BITS","code":3408,"ext":"webgl","value":4},{"name":"RED_BITS","code":3410,"ext":"webgl","value":8},{"name":"GREEN_BITS","code":3411,"ext":"webgl","value":8},{"name":"BLUE_BITS","code":3412,"ext":"webgl","value":8},{"name":"ALPHA_BITS","code":3413,"ext":"webgl","value":8},{"name":"DEPTH_BITS","code":3414,"ext":"webgl","value":24},{"name":"STENCIL_BITS","code":3415,"ext":"webgl","value":0},{"name":"POLYGON_OFFSET_UNITS","code":10752,"ext":"webgl","value":0},{"name":"POLYGON_OFFSET_FACTOR","code":32824,"ext":"webgl","value":0},{"name":"SAMPLE_BUFFERS","code":32936,"ext":"webgl","value":1},{"name":"SAMPLES","code":32937,"ext":"webgl","value":8},{"name":"SAMPLE_COVERAGE_VALUE","code":32938,"ext":"webgl","value":1},{"name":"SAMPLE_COVERAGE_INVERT","code":32939,"ext":"webgl","value":false},{"name":"COMPRESSED_TEXTURE_FORMATS","code":34467,"ext":"webgl","value":[]},{"name":"GENERATE_MIPMAP_HINT","code":33170,"ext":"webgl","value":4352},{"name":"MAX_VERTEX_ATTRIBS","code":34921,"ext":"webgl","value":16},{"name":"MAX_VERTEX_UNIFORM_VECTORS","code":36347,"ext":"webgl","value":4096},{"name":"MAX_VARYING_VECTORS","code":36348,"ext":"webgl","value":30},{"name":"MAX_COMBINED_TEXTURE_IMAGE_UNITS","code":35661,"ext":"webgl","value":32},{"name":"MAX_VERTEX_TEXTURE_IMAGE_UNITS","code":35660,"ext":"webgl","value":16},{"name":"MAX_TEXTURE_IMAGE_UNITS","code":34930,"ext":"webgl","value":16},{"name":"MAX_FRAGMENT_UNIFORM_VECTORS","code":36349,"ext":"webgl","value":1024},{"name":"SHADING_LANGUAGE_VERSION","code":35724,"ext":"webgl","value":"WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)"},{"name":"VENDOR","code":7936,"ext":"webgl","value":"WebKit"},{"name":"RENDERER","code":7937,"ext":"webgl","value":"WebKit WebGL"},{"name":"VERSION","code":7938,"ext":"webgl","value":"WebGL 1.0 (OpenGL ES 2.0 Chromium)"},{"name":"MAX_CUBE_MAP_TEXTURE_SIZE","code":34076,"ext":"webgl","value":16384},{"name":"ACTIVE_TEXTURE","code":34016,"ext":"webgl","value":33984},{"name":"IMPLEMENTATION_COLOR_READ_TYPE","code":35738,"ext":"webgl","value":5121},{"name":"IMPLEMENTATION_COLOR_READ_FORMAT","code":35739,"ext":"webgl","value":6408},{"name":"MAX_RENDERBUFFER_SIZE","code":34024,"ext":"webgl","value":16384},{"name":"UNPACK_FLIP_Y_WEBGL","code":37440,"ext":"webgl","value":false},{"name":"UNPACK_PREMULTIPLY_ALPHA_WEBGL","code":37441,"ext":"webgl","value":false},{"name":"UNPACK_COLORSPACE_CONVERSION_WEBGL","code":37443,"ext":"webgl","value":37444},{"name":"TIMESTAMP_EXT","code":36392,"ext":"EXT_disjoint_timer_query","value":0},{"name":"GPU_DISJOINT_EXT","code":36795,"ext":"EXT_disjoint_timer_query","value":false},{"name":"MAX_TEXTURE_MAX_ANISOTROPY_EXT","code":34047,"ext":"EXT_texture_filter_anisotropic","value":16},{"name":"MAX_TEXTURE_MAX_ANISOTROPY_EXT","code":34047,"ext":"WEBKIT_EXT_texture_filter_anisotropic","value":16},{"name":"FRAGMENT_SHADER_DERIVATIVE_HINT_OES","code":35723,"ext":"OES_standard_derivatives","value":4352},{"name":"DRAW_BUFFER0_WEBGL","code":34853,"ext":"WEBGL_draw_buffers","value":1029},{"name":"DRAW_BUFFER1_WEBGL","code":34854,"ext":"WEBGL_draw_buffers","value":1029},{"name":"DRAW_BUFFER2_WEBGL","code":34855,"ext":"WEBGL_draw_buffers","value":1029},{"name":"DRAW_BUFFER3_WEBGL","code":34856,"ext":"WEBGL_draw_buffers","value":1029},{"name":"DRAW_BUFFER4_WEBGL","code":34857,"ext":"WEBGL_draw_buffers","value":1029},{"name":"DRAW_BUFFER5_WEBGL","code":34858,"ext":"WEBGL_draw_buffers","value":1029},{"name":"DRAW_BUFFER6_WEBGL","code":34859,"ext":"WEBGL_draw_buffers","value":1029},{"name":"DRAW_BUFFER7_WEBGL","code":34860,"ext":"WEBGL_draw_buffers","value":1029},{"name":"MAX_COLOR_ATTACHMENTS_WEBGL","code":36063,"ext":"WEBGL_draw_buffers","value":8},{"name":"MAX_DRAW_BUFFERS_WEBGL","code":34852,"ext":"WEBGL_draw_buffers","value":8}]`

WebGL 2 Params I know of:
`"webGl2Params":[{"name":"READ_BUFFER","code":3074,"ext":"webgl","value":1029},{"name":"UNPACK_ROW_LENGTH","code":3314,"ext":"webgl","value":0},{"name":"UNPACK_SKIP_ROWS","code":3315,"ext":"webgl","value":0},{"name":"UNPACK_SKIP_PIXELS","code":3316,"ext":"webgl","value":0},{"name":"PACK_ROW_LENGTH","code":3330,"ext":"webgl","value":0},{"name":"PACK_SKIP_ROWS","code":3331,"ext":"webgl","value":0},{"name":"PACK_SKIP_PIXELS","code":3332,"ext":"webgl","value":0},{"name":"UNPACK_SKIP_IMAGES","code":32877,"ext":"webgl","value":0},{"name":"UNPACK_IMAGE_HEIGHT","code":32878,"ext":"webgl","value":0},{"name":"MAX_3D_TEXTURE_SIZE","code":32883,"ext":"webgl","value":2048},{"name":"MAX_ELEMENTS_VERTICES","code":33000,"ext":"webgl","value":2147483647},{"name":"MAX_ELEMENTS_INDICES","code":33001,"ext":"webgl","value":2147483647},{"name":"MAX_TEXTURE_LOD_BIAS","code":34045,"ext":"webgl","value":2},{"name":"MAX_DRAW_BUFFERS","code":34852,"ext":"webgl","value":8},{"name":"DRAW_BUFFER0","code":34853,"ext":"webgl","value":1029},{"name":"DRAW_BUFFER1","code":34854,"ext":"webgl","value":1029},{"name":"DRAW_BUFFER2","code":34855,"ext":"webgl","value":1029},{"name":"DRAW_BUFFER3","code":34856,"ext":"webgl","value":1029},{"name":"DRAW_BUFFER4","code":34857,"ext":"webgl","value":1029},{"name":"DRAW_BUFFER5","code":34858,"ext":"webgl","value":1029},{"name":"DRAW_BUFFER6","code":34859,"ext":"webgl","value":1029},{"name":"DRAW_BUFFER7","code":34860,"ext":"webgl","value":1029},{"name":"MAX_FRAGMENT_UNIFORM_COMPONENTS","code":35657,"ext":"webgl","value":4096},{"name":"MAX_VERTEX_UNIFORM_COMPONENTS","code":35658,"ext":"webgl","value":16384},{"name":"FRAGMENT_SHADER_DERIVATIVE_HINT","code":35723,"ext":"webgl","value":4352},{"name":"MAX_ARRAY_TEXTURE_LAYERS","code":35071,"ext":"webgl","value":2048},{"name":"MIN_PROGRAM_TEXEL_OFFSET","code":35076,"ext":"webgl","value":-8},{"name":"MAX_PROGRAM_TEXEL_OFFSET","code":35077,"ext":"webgl","value":7},{"name":"MAX_VARYING_COMPONENTS","code":35659,"ext":"webgl","value":120},{"name":"MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS","code":35968,"ext":"webgl","value":4},{"name":"RASTERIZER_DISCARD","code":35977,"ext":"webgl","value":false},{"name":"MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS","code":35978,"ext":"webgl","value":120},{"name":"MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS","code":35979,"ext":"webgl","value":4},{"name":"MAX_COLOR_ATTACHMENTS","code":36063,"ext":"webgl","value":8},{"name":"MAX_SAMPLES","code":36183,"ext":"webgl","value":8},{"name":"MAX_VERTEX_UNIFORM_BLOCKS","code":35371,"ext":"webgl","value":12},{"name":"MAX_FRAGMENT_UNIFORM_BLOCKS","code":35373,"ext":"webgl","value":12},{"name":"MAX_COMBINED_UNIFORM_BLOCKS","code":35374,"ext":"webgl","value":24},{"name":"MAX_UNIFORM_BUFFER_BINDINGS","code":35375,"ext":"webgl","value":24},{"name":"MAX_UNIFORM_BLOCK_SIZE","code":35376,"ext":"webgl","value":65536},{"name":"MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS","code":35377,"ext":"webgl","value":212992},{"name":"MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS","code":35379,"ext":"webgl","value":200704},{"name":"UNIFORM_BUFFER_OFFSET_ALIGNMENT","code":35380,"ext":"webgl","value":256},{"name":"MAX_VERTEX_OUTPUT_COMPONENTS","code":37154,"ext":"webgl","value":120},{"name":"MAX_FRAGMENT_INPUT_COMPONENTS","code":37157,"ext":"webgl","value":120},{"name":"MAX_SERVER_WAIT_TIMEOUT","code":37137,"ext":"webgl","value":0},{"name":"TRANSFORM_FEEDBACK_PAUSED","code":36387,"ext":"webgl","value":false},{"name":"TRANSFORM_FEEDBACK_ACTIVE","code":36388,"ext":"webgl","value":false},{"name":"MAX_ELEMENT_INDEX","code":36203,"ext":"webgl","value":4294967294},{"name":"MAX_CLIENT_WAIT_TIMEOUT_WEBGL","code":37447,"ext":"webgl","value":0},{"name":"BLEND_EQUATION","code":32777,"ext":"webgl","value":32774},{"name":"BLEND_EQUATION_RGB","code":32777,"ext":"webgl","value":32774},{"name":"BLEND_EQUATION_ALPHA","code":34877,"ext":"webgl","value":32774},{"name":"BLEND_DST_RGB","code":32968,"ext":"webgl","value":0},{"name":"BLEND_SRC_RGB","code":32969,"ext":"webgl","value":1},{"name":"BLEND_DST_ALPHA","code":32970,"ext":"webgl","value":0},{"name":"BLEND_SRC_ALPHA","code":32971,"ext":"webgl","value":1},{"name":"BLEND_COLOR","code":32773,"ext":"webgl","value":[0,0,0,0]},{"name":"CULL_FACE","code":2884,"ext":"webgl","value":false},{"name":"BLEND","code":3042,"ext":"webgl","value":false},{"name":"DITHER","code":3024,"ext":"webgl","value":true},{"name":"STENCIL_TEST","code":2960,"ext":"webgl","value":false},{"name":"DEPTH_TEST","code":2929,"ext":"webgl","value":false},{"name":"SCISSOR_TEST","code":3089,"ext":"webgl","value":false},{"name":"POLYGON_OFFSET_FILL","code":32823,"ext":"webgl","value":false},{"name":"SAMPLE_ALPHA_TO_COVERAGE","code":32926,"ext":"webgl","value":false},{"name":"SAMPLE_COVERAGE","code":32928,"ext":"webgl","value":false},{"name":"LINE_WIDTH","code":2849,"ext":"webgl","value":1},{"name":"ALIASED_POINT_SIZE_RANGE","code":33901,"ext":"webgl","value":[1,1024]},{"name":"ALIASED_LINE_WIDTH_RANGE","code":33902,"ext":"webgl","value":[1,1]},{"name":"CULL_FACE_MODE","code":2885,"ext":"webgl","value":1029},{"name":"FRONT_FACE","code":2886,"ext":"webgl","value":2305},{"name":"DEPTH_RANGE","code":2928,"ext":"webgl","value":[0,1]},{"name":"DEPTH_WRITEMASK","code":2930,"ext":"webgl","value":true},{"name":"DEPTH_CLEAR_VALUE","code":2931,"ext":"webgl","value":1},{"name":"DEPTH_FUNC","code":2932,"ext":"webgl","value":513},{"name":"STENCIL_CLEAR_VALUE","code":2961,"ext":"webgl","value":0},{"name":"STENCIL_FUNC","code":2962,"ext":"webgl","value":519},{"name":"STENCIL_FAIL","code":2964,"ext":"webgl","value":7680},{"name":"STENCIL_PASS_DEPTH_FAIL","code":2965,"ext":"webgl","value":7680},{"name":"STENCIL_PASS_DEPTH_PASS","code":2966,"ext":"webgl","value":7680},{"name":"STENCIL_REF","code":2967,"ext":"webgl","value":0},{"name":"STENCIL_VALUE_MASK","code":2963,"ext":"webgl","value":2147483647},{"name":"STENCIL_WRITEMASK","code":2968,"ext":"webgl","value":2147483647},{"name":"STENCIL_BACK_FUNC","code":34816,"ext":"webgl","value":519},{"name":"STENCIL_BACK_FAIL","code":34817,"ext":"webgl","value":7680},{"name":"STENCIL_BACK_PASS_DEPTH_FAIL","code":34818,"ext":"webgl","value":7680},{"name":"STENCIL_BACK_PASS_DEPTH_PASS","code":34819,"ext":"webgl","value":7680},{"name":"STENCIL_BACK_REF","code":36003,"ext":"webgl","value":0},{"name":"STENCIL_BACK_VALUE_MASK","code":36004,"ext":"webgl","value":2147483647},{"name":"STENCIL_BACK_WRITEMASK","code":36005,"ext":"webgl","value":2147483647},{"name":"VIEWPORT","code":2978,"ext":"webgl","value":[0,0,300,150]},{"name":"SCISSOR_BOX","code":3088,"ext":"webgl","value":[0,0,300,150]},{"name":"COLOR_CLEAR_VALUE","code":3106,"ext":"webgl","value":[0,0,0,0]},{"name":"COLOR_WRITEMASK","code":3107,"ext":"webgl","value":[true,true,true,true]},{"name":"UNPACK_ALIGNMENT","code":3317,"ext":"webgl","value":4},{"name":"PACK_ALIGNMENT","code":3333,"ext":"webgl","value":4},{"name":"MAX_TEXTURE_SIZE","code":3379,"ext":"webgl","value":16384},{"name":"MAX_VIEWPORT_DIMS","code":3386,"ext":"webgl","value":[32767,32767]},{"name":"SUBPIXEL_BITS","code":3408,"ext":"webgl","value":4},{"name":"RED_BITS","code":3410,"ext":"webgl","value":8},{"name":"GREEN_BITS","code":3411,"ext":"webgl","value":8},{"name":"BLUE_BITS","code":3412,"ext":"webgl","value":8},{"name":"ALPHA_BITS","code":3413,"ext":"webgl","value":8},{"name":"DEPTH_BITS","code":3414,"ext":"webgl","value":24},{"name":"STENCIL_BITS","code":3415,"ext":"webgl","value":0},{"name":"POLYGON_OFFSET_UNITS","code":10752,"ext":"webgl","value":0},{"name":"POLYGON_OFFSET_FACTOR","code":32824,"ext":"webgl","value":0},{"name":"SAMPLE_BUFFERS","code":32936,"ext":"webgl","value":1},{"name":"SAMPLES","code":32937,"ext":"webgl","value":8},{"name":"SAMPLE_COVERAGE_VALUE","code":32938,"ext":"webgl","value":1},{"name":"SAMPLE_COVERAGE_INVERT","code":32939,"ext":"webgl","value":false},{"name":"COMPRESSED_TEXTURE_FORMATS","code":34467,"ext":"webgl","value":[]},{"name":"GENERATE_MIPMAP_HINT","code":33170,"ext":"webgl","value":4352},{"name":"MAX_VERTEX_ATTRIBS","code":34921,"ext":"webgl","value":16},{"name":"MAX_VERTEX_UNIFORM_VECTORS","code":36347,"ext":"webgl","value":4096},{"name":"MAX_VARYING_VECTORS","code":36348,"ext":"webgl","value":30},{"name":"MAX_COMBINED_TEXTURE_IMAGE_UNITS","code":35661,"ext":"webgl","value":32},{"name":"MAX_VERTEX_TEXTURE_IMAGE_UNITS","code":35660,"ext":"webgl","value":16},{"name":"MAX_TEXTURE_IMAGE_UNITS","code":34930,"ext":"webgl","value":16},{"name":"MAX_FRAGMENT_UNIFORM_VECTORS","code":36349,"ext":"webgl","value":1024},{"name":"SHADING_LANGUAGE_VERSION","code":35724,"ext":"webgl","value":"WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)"},{"name":"VENDOR","code":7936,"ext":"webgl","value":"WebKit"},{"name":"RENDERER","code":7937,"ext":"webgl","value":"WebKit WebGL"},{"name":"VERSION","code":7938,"ext":"webgl","value":"WebGL 2.0 (OpenGL ES 3.0 Chromium)"},{"name":"MAX_CUBE_MAP_TEXTURE_SIZE","code":34076,"ext":"webgl","value":16384},{"name":"ACTIVE_TEXTURE","code":34016,"ext":"webgl","value":33984},{"name":"IMPLEMENTATION_COLOR_READ_TYPE","code":35738,"ext":"webgl","value":5121},{"name":"IMPLEMENTATION_COLOR_READ_FORMAT","code":35739,"ext":"webgl","value":6408},{"name":"MAX_RENDERBUFFER_SIZE","code":34024,"ext":"webgl","value":16384},{"name":"UNPACK_FLIP_Y_WEBGL","code":37440,"ext":"webgl","value":false},{"name":"UNPACK_PREMULTIPLY_ALPHA_WEBGL","code":37441,"ext":"webgl","value":false},{"name":"UNPACK_COLORSPACE_CONVERSION_WEBGL","code":37443,"ext":"webgl","value":37444},{"name":"TIMESTAMP_EXT","code":36392,"ext":"EXT_disjoint_timer_query_webgl2","value":0},{"name":"GPU_DISJOINT_EXT","code":36795,"ext":"EXT_disjoint_timer_query_webgl2","value":false},{"name":"MAX_TEXTURE_MAX_ANISOTROPY_EXT","code":34047,"ext":"EXT_texture_filter_anisotropic","value":16},{"name":"MAX_VIEWS_OVR","code":38449,"ext":"OVR_multiview2","value":4}]`

**Comment by abrahamjuliot** [comment]
This is very helpful. I can confirm I have all except a small bundle. 

Looks like these are acquired from extensions. I'll take a closer look.

```
DRAW_BUFFER0_WEBGL
DRAW_BUFFER1_WEBGL
DRAW_BUFFER2_WEBGL
DRAW_BUFFER3_WEBGL
DRAW_BUFFER4_WEBGL
DRAW_BUFFER5_WEBGL
DRAW_BUFFER6_WEBGL
DRAW_BUFFER7_WEBGL
FRAGMENT_SHADER_DERIVATIVE_HINT_OES
GPU_DISJOINT_EXT
MAX_COLOR_ATTACHMENTS_WEBGL
MAX_VIEWS_OVR
TIMESTAMP_EXT
```
--
This will get the max params (on webgl2 for example), however, this method of testing every enum in the prototype generates an excessive amount of 'invalid' enum warnings in the console. Chrome logs, `...too many errors, no more errors will be reported...` 😂

I plan to reserve this global search for the test page.

```js
const canvas = document.createElement('canvas')
const gl = canvas.getContext('webgl2')
const params = Object.keys(WebGL2RenderingContext.prototype)
.filter(key => key.toUpperCase() == key)
.sort()
.reduce((acc, key) => {
    const val = gl.getParameter(gl[key])
    if (val !== null) {
        acc[key] = val
    }
    return acc
},{})
console.log(params)
```

**Comment by abrahamjuliot** [comment]
This captures all non null extension params
```js
const getExtensions = gl => {
    if (!gl) {
        return {
            data: {},
            extensions: []
        }
    }
    const extensions = gl.getSupportedExtensions() || []
    let data = {}
    try {
        data = extensions.reduce((acc, key) => {
            const ext = gl.getExtension(key)
            const constants = Object.keys(Object.getPrototypeOf(ext))
            return {
                ...acc,
                ...constants.reduce((acc, x) => {
                    const param = gl.getParameter(ext[x])
                    if (param !== null) {
                        acc[x] = param
                    }
                    return acc
                }, {})
            }
        }, {})
    } catch (error) {}

    return {
        data,
        extensions
    }
}

```

**Comment by abrahamjuliot** [comment]
This should go live in next months' release:
- 162 params: I left out a few extension params (noted above). I may add these later.
- extensions and params are now `webgl` and `webgl2` combined
- image is improved and displayed
- pixel fingerprint added
- `webgl2` image and pixel fingerprint is only shown if it differs from `webgl`
- if `webgl2` params differ from `webgl` (not counting version params), then this is exposed as trash output.
