### ISSUE TITLE
Palemoon don't work

### ISSUE THREAD

**Issue by oroscobob** [abrahamjuliot/creepjs#121]
Don't work: Palemoon, Chrome70"-", iridium70"-", etc

**Comment by abrahamjuliot** [comment]
Pale Moon and Iridium should work on the latest releases. I'm mostly focused on testing the latest stable and dev channels, but I do want to support builds released within the last year. Chromium builds < 84 are not fully supported.

**Comment by oroscobob** [comment]
Okay, I get it. You made a very cool script. Thank you.
