### ISSUE TITLE
Provide results as JSON object

### ISSUE THREAD

**Issue by prescience-data** [abrahamjuliot/creepjs#124]
Would be great to be able to extract a JSON representation of the results from a named div ie 
```html
<div id="results" style="display: none;"></div>
<script>
// ... run tests
document.getElementById("results").innerHTML = JSON.stringify(results)
</script>
```

If there is any interest I can do a PR but I figure you might prefer to implement yourself etc...

**Comment by abrahamjuliot** [comment]
I like this concept, but the size of the JSON object is overwhelming. As an alternative, I added a patch that exposes the fingerprint objects to the window. This provides direct access to extract or interact with the objects. Let me know if that is useful. I open to a JSON innerHTML view, but I need to think that through. Pull requests are always welcome.

```js
window.Fingerprint // all metrics
window.Creep // stable metrics
```

**Comment by prescience-data** [comment]
The `window` implementation is actually much better / cleaner than a div tag.
Thanks!
