### ISSUE TITLE
Crash in canary

### ISSUE THREAD

**Issue by Niek** [abrahamjuliot/creepjs#133]
CreepJS is crashing in the latest Chrome canary (`92.0.4512.0 (Official Build) canary (x86_64)`) for me:

<img width="765" alt="Screen Shot 2021-05-19 at 17 11 14" src="https://user-images.githubusercontent.com/213140/118837603-49228800-b8c5-11eb-8845-283bf6ff63c2.png">

Not sure if it's a CreepJS issue or if canary is just buggy.

**Comment by abrahamjuliot** [comment]
It appears `MediaSource.isTypeSupported('audio/mpeg; codecs="mp3"')` is causing this. For now, I'm removing that mimeType. Let me know if that fixes it on your end. It's live on the [dev site](https://creepjs--abrahamjuliot.repl.co). If this mimeType crash persists, I will have this merged to the github site in a June release.

**Comment by Niek** [comment]
I can confirm this is fixed on the dev site. I have opened a bug report at the Chromium tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1211241
