### ISSUE TITLE
Chromium Crash 

### ISSUE THREAD

**Issue by Klyado** [abrahamjuliot/creepjs#141]
Hi, 

I might be missing something but I can't access the result by using this simple code 

`const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://abrahamjuliot.github.io/creepjs/');
  // other actions...
  await browser.close();
})();`

It seems to make the browser crash 🤔

<img width="1183" alt="Screenshot 2021-07-22 at 20 17 14" src="https://user-images.githubusercontent.com/34454140/126689409-0c5cf5d0-1c44-4b62-9275-01b66c387bd8.png">

**Comment by abrahamjuliot** [comment]
Thank you for reporting this. Hmmm... I'm not encountering this on my end. What version of chromium are you on?

This might be related #133. If its the same issue, the browser should crash the same if you run the test at [https://privacy-test-pages.glitch.me/privacy-protections/fingerprinting](https://privacy-test-pages.glitch.me/privacy-protections/fingerprinting).

**Comment by Klyado** [comment]
Hi! 

You're welcome! 
It's Chrome Version 92.0.4512.0 (Developer Build) (x86_64)

As regards the test at https://privacy-test-pages.glitch.me/privacy-protections/fingerprinting/ I don't have any error and it doesn't crash 🤔.

![Screenshot 2021-07-23 at 12 23 45](https://user-images.githubusercontent.com/34454140/126769527-509eb9db-5af3-46dd-badf-8ec4490bf44c.png)

As you can see the website loads well but then it crashes at the "computing" step


https://user-images.githubusercontent.com/34454140/126769713-5f834914-f004-4435-98ca-c9389d966c9d.mov

**Comment by abrahamjuliot** [comment]
> As regards the test at https://privacy-test-pages.glitch.me/privacy-protections/fingerprinting/ I don't have any error and it doesn't crash 🤔.

What happens when you click "Start the test" there. It should crash.

If it crashes, then this is likely the `MediaSource.isTypeSupported('audio/mpeg; codecs="mp3"')` issue we encountered on Canary in the same build, 92.0.4512.0.

**Comment by abrahamjuliot** [comment]
Closing for now, but let me know if you encounter this in another build version. We could consider removing the mp3 codec known to cause this.
