### ISSUE TITLE
Repeated identical fingerprint across many devices.

### ISSUE THREAD

**Issue by SkewedZeppelin** [abrahamjuliot/creepjs#144]
I have been able to achieve the same exact fingerprint across three sets of devices:
- across my desktop and laptop and a third spare machine which are all completely different hardware wise
- across two LG G3 phones
- across two Nexus 4 phones, and nearly identical on 2 more except for emoji test
<details>
<summary>Pictures</summary>

![d852](https://user-images.githubusercontent.com/8296104/127938740-bd25c4ef-1c0f-48bf-8ba9-68356eb24422.jpg)
![mako](https://user-images.githubusercontent.com/8296104/127938742-e11edc02-16da-4e7f-bada-747c77742e8e.jpg)

</details>

**Comment by abrahamjuliot** [comment]
Thank you for reporting this. This is within reason if Firefox RFP is on and when all devices are the same machine class (Android in this case). If the script detects resistance, it reduces entropy to maintain stability and tries to preserve the machine class where achievable (workers, fonts, navigator, or silently via emojis and system styles). If we resist, we should only encounter intersections within the same machine class: Android, Apple, Linux, or Windows.

Regarding Firefox, at the moment, I do not track screen dimension entropy if Firefox RFP is on. If it's on, the screen size is the viewport size, which is too loose on desktop screens, Chromebooks running Android and soon Windows 11 running Android apps (switching to full/split screen changes the viewport fingerprint).

I will keep an eye on this and revisit. My goal is to find unprotected device entropy that is not easy to resist.

**Comment by SkewedZeppelin** [comment]
Those were all with RFP (Mull), but here is a picture with vanilla Fennec F-Droid (effectively vanilla FF), no RFP at all:

<details>
<summary>Picture</summary>

![g3-no_rfp](https://user-images.githubusercontent.com/8296104/127959485-15dc3576-bf4f-4614-a2f9-e0062ef4e4f4.jpg)

</details>

**Comment by abrahamjuliot** [comment]
In Firefox, this too is within reason if the devices and browser engine are near identical. To reach this, timezone, language, screen dimensions, android version, platform string, number of cores, gpu renderer, type of media devices, preferred color scheme and browser engine each must match.

**Comment by SkewedZeppelin** [comment]
Thank you for clarifying.
