### ISSUE TITLE
Crashing Firefox on Linux

### ISSUE THREAD

**Issue by Niek** [abrahamjuliot/creepjs#148]
Latest CreepJS crashes Firefox on Linux:

<img width="1897" alt="Screenshot 2021-09-06 at 18 53 45" src="https://user-images.githubusercontent.com/213140/132330820-6d448593-8b87-4c7d-8b02-e31a077ac4fb.png">

I haven't been able to figure out yet which call is causing it.

Firefox on macOS works fine in my tests.

**Comment by abrahamjuliot** [comment]
Thank you for reporting this. I've had no success reproducing this in Linux Lite/Ubuntu 64-bit. I tested using a clean installation of both Firefox 91.0.2 and Nightly 94 (with and without RFP). Which Linux distro and Firefox version are you on, and does this crash occur in Nightly?

**Comment by Niek** [comment]
This is on Ubuntu with the latest nightly Firefox:
<img width="618" alt="Screenshot 2021-09-13 at 10 50 07" src="https://user-images.githubusercontent.com/213140/133055081-62a2f02c-dd04-485b-9dba-de1a4c141384.png">

The error message I'm seeing is:
```bash
###!!! [Parent][MessageChannel] Error: (msgtype=0x850007,name=PSharedWorker::Msg_Terminate) Channel error: cannot send/recv
```

So probably a bug in the Firefox RTC code, I guess I should file a bugreport there.
