### ISSUE TITLE
Github Sponsors Page

### ISSUE THREAD

**Issue by prescience-data** [abrahamjuliot/creepjs#161]
Hey @abrahamjuliot !
Have you thought of setting up a Github sponsors page?
https://github.com/sponsors

**Comment by abrahamjuliot** [comment]
Nice. Thanks for the tip. I have not given it much thought. I will definitely look into this. Looks pretty cool.

**Comment by treyvanes** [comment]
We could offer some sponsorship if you set up a Github sponsors page.

**Comment by abrahamjuliot** [comment]
@treyvanes Thank you. I'm leaning toward no Github sponors page (just my personal preference), but wow I appreciate the offer and support.
