### ISSUE TITLE
README Suggestions 

### ISSUE THREAD

**Issue by v-0-d** [abrahamjuliot/creepjs#165]
At the moment the script only show the browsers weak points without suggesting possible solutions that can be implemented by add-on or browser developers.

Would it be possible to add a suggestions section in the README with information that developers and end users can use to protect themselves or implement counter-measures in their codes?

**Comment by abrahamjuliot** [comment]
Suggesting solutions and/or counter-measures is outside the scope of this project. But, questions on specific metric are always welcome.

**Comment by abrahamjuliot** [comment]
Closing, but feel free to discuss
