### ISSUE TITLE
Workers page crashes when webgl is unavailable

### ISSUE THREAD

**Issue by momala454** [abrahamjuliot/creepjs#166]
This part of the code broke at the last line
```js
const canvasOffscreenWebgl = new OffscreenCanvas(256, 256)
			const contextWebgl = canvasOffscreenWebgl.getContext('webgl')
			const renererInfo = contextWebgl.getExtension('WEBGL_debug_renderer_info')
			webglVendor = contextWebgl.getParameter(renererInfo.UNMASKED_VENDOR_WEBGL)
```

with the error "ReferenceError: opts is not defined" pointing to the last line. (i don't know why it says "opts" as the line doesn't contains opts)
So https://abrahamjuliot.github.io/creepjs/tests/workers.html appears empty when webgl is not working

**Comment by momala454** [comment]
sorry, it was a problem from my side, not related to creepjs.

**Comment by abrahamjuliot** [comment]
Sounds good. 👍 Glad that got resolved.
