### ISSUE TITLE
Page crash in Safari

### ISSUE THREAD

**Issue by Niek** [abrahamjuliot/creepjs#174]
Opening CreepJS in the latest stable Safari (15.3 - 17612.4.9.1.5) crashes the whole tab (after a page flicker), the following message appears:
<img width="882" alt="Screenshot 2022-02-15 at 15 25 17" src="https://user-images.githubusercontent.com/213140/154081748-9a446bbf-4186-4a23-ba40-42621f44d901.png">

No error messages in the debugger console, so it might be hard to find the root cause.

**Comment by abrahamjuliot** [comment]
🤔 This appears to occur during webgl rendering at or following `gl.linkProgram`, and no error gets thrown on crash. Near all samples at [webglsamples.org](https://webglsamples.org/) are encountering the crash too.

These bugs appear related:
- https://bugs.webkit.org/show_bug.cgi?id=235515
- https://bugs.webkit.org/show_bug.cgi?id=235594

@kkinnunen-apple fyi

**Comment by Niek** [comment]
Hmm, I tried the samples at https://github.com/WebGLSamples/WebGLSamples.github.io#webgl-samples but none of them crash for me. Same for the URLs mentioned in the bug reports - those might be separate issues on the mobile Safari browser. On the desktop browser, I haven't been able to find another page that crashes Safari yet.

**Comment by abrahamjuliot** [comment]
I'm guessing the webgl sample crashes occur due to my low-end machine... fpjs, browserleaks, amiunique, and coveryourtracks all crash via the same webgl method (triggers at `gl.drawArrays`). 

Unrelated to webgl, the use of `FontFace.load()` in workers crashes, but not in 15.4.

**Comment by abrahamjuliot** [comment]
I just reduced the data captured in the worker scope. I'm not sure if that resolved this, but the issue appears gone in 15.3.

Closing for now, but let me know if the issue persists.
