### ISSUE TITLE
How to bundle or compress creep in the right way?

### ISSUE THREAD

**Issue by Zen33** [abrahamjuliot/creepjs#179]
When I  try to use rollup plugin to compress creep file, the creepjs result is not right especially  puppeteer-extra is not detected, the extension of lies is 'undefined'.

**Comment by Zen33** [comment]
Thanks for your reply. The rollup configuration you give simply packs all files into one file (iife mode), but without compression and browser version compatibility (such as ES5). When I tried to introduce the Babel or Terser plugin package code to work with more browsers, creepjs didn't work. What does creepjs current compatible browser versions?

**Comment by abrahamjuliot** [comment]
The script runs back to Firefox 70 and Chrome 75 (October 2019 era), but es2017 compression should not break the code.

**Comment by Zen33** [comment]
When I use an earlier version of chrome, I get a syntax failure or compatibility issues. Is there a way support more versions of browsers, like babel stage, so that more browser versions could be supported and widely available.

**Comment by Zen33** [comment]
When I use terser plugin to compress code, puppeteer undetectable.

**Comment by abrahamjuliot** [comment]
> support more versions

That's possible. Need to go through each file and refactor or polyfill some methods. I'm considering this task. It would be nice to test older browsers and have compression built in.

**Comment by abrahamjuliot** [comment]
Terser might be replacing depreciated methods like `__proto__` which is used in the detection. Compression compatibility is not an immediate or long term goal, but I may look into that at some point.

**Comment by Zen33** [comment]
> > support more versions
> 
> That's possible. Need to go through each file and refactor or polyfill some methods. I'm considering this task. It would be nice to test older browsers and have compression built in.

I'm looking forward to it, hopefully not too long, thanks for reply again:)
