### ISSUE TITLE
CreepJS cannot detect latest build of Puppeteer Extra Stealth (puppeteer-extra-plugin-stealth@2.10.0)

### ISSUE THREAD

**Issue by treyvanes** [abrahamjuliot/creepjs#185]
CreepJS is able to detect the previous build of Puppeteer Extra Stealth (puppeteer-extra-plugin-stealth@2.9.0), but cannot detect the latest build (puppeteer-extra-plugin-stealth@2.10.0) which was released on June 20.

Previous build (puppeteer-extra-plugin-stealth@2.9.0):

![image](https://user-images.githubusercontent.com/84434559/174803989-405f7486-7b86-42d5-83f7-e5972f51db59.png)

Latest build (puppeteer-extra-plugin-stealth@2.10.0):

![image](https://user-images.githubusercontent.com/84434559/174804414-cdf76419-57ee-4d16-a69a-1a91902d0d91.png)

Here's a simple bot to test this:

    // npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
    const puppeteer = require('puppeteer-extra');
    const StealthPlugin = require('puppeteer-extra-plugin-stealth');
    puppeteer.use(StealthPlugin());

    puppeteer.launch({ headless: false }).then(async browser => {

      let page = await browser.newPage();
      await page.goto("https://abrahamjuliot.github.io/creepjs/");

    });

**Comment by abrahamjuliot** [comment]
Thank you @treyvanes. Support added.

**Comment by kashif-ghafoor** [comment]
I am using puppeteer-extra-stealth version ^2.11.1. But still, creepjs is able to detect my bot. any recommendations?
![image](https://user-images.githubusercontent.com/58185339/188508436-ac3b5d57-a77e-4f7d-ae48-8773e00f666b.png)

**Comment by abrahamjuliot** [comment]
There are experts who specialize in finding solutions. I'm just a cat laying out some cheese on my mousetraps. You can still do a lot with stealth plugin. I would not be too concerned it gets detected here. This is just a specialized test only to show detection is possible.

**Comment by KMarfatia17** [comment]
is 80 percent stealth okay ?


![Screenshot 2023-06-16 at 5 01 13 PM](https://github.com/abrahamjuliot/creepjs/assets/96575468/7b65ba7c-0c10-458b-9e25-df2a52cb27d7)

![Screenshot 2023-06-16 at 5 16 38 PM](https://github.com/abrahamjuliot/creepjs/assets/96575468/cd62e1da-dd4c-4b25-97e1-297b8784713e)

why does they blur trust score and lies detection in puppeteer chromium ? like this.
![Screenshot 2023-06-16 at 5 16 30 PM](https://github.com/abrahamjuliot/creepjs/assets/96575468/37504db4-0531-4690-9196-f73c7121e8e2)

**Comment by KMarfatia17** [comment]
can you please tell me why is the trust score and lie detection is blurred ?

**Comment by abrahamjuliot** [comment]
80% is okay. I'll take a look. Indefinite blur might be due to an error. Do you have any standard APIs disabled? What do you see on the console?

**Comment by KMarfatia17** [comment]
![Screenshot 2023-06-19 at 10 21 42 AM](https://github.com/abrahamjuliot/creepjs/assets/96575468/b910d3ba-280a-495d-85f9-7c90c28a1aca)

getting this on console.

**Comment by abrahamjuliot** [comment]
Hm… Do you encounter the same issue on the latest Chrome in headfull mode?

**Comment by KMarfatia17** [comment]
yes

**Comment by KMarfatia17** [comment]
![Screenshot 2023-06-21 at 4 03 24 PM](https://github.com/abrahamjuliot/creepjs/assets/96575468/d2ddc156-520c-4aeb-ab0c-154ba28f912d)


can you help me with this error? its getting lies because of this error "failed object toString error"

**Comment by abrahamjuliot** [comment]
The console output looks okay. "error" just means we simulated a specific error to analyze and test against. The browser then produced something unexpected. It's normalized, named, and shared in this case. I don't recommend changing it, but I don't recommend much, aside from owning a cat. I'm only expert in knowing the importance of owning a cat.

I can't speak to the hang on the API fetch, but I need to implement a timeout and throw an error there. If it's occurring on your system on all Chrome browsers, it might be a network issue (maybe DNS or IP network?).
