### ISSUE TITLE
Social Media Login Detection as a part for being more precise with bot detection

### ISSUE THREAD

**Issue by vis2021t** [abrahamjuliot/creepjs#187]
I was just thinking about being a device instead of thinking as human or bot, I came across which is Image-based cross-origin login detection,

I think a bot wont be logged into facebook and other big social media who refuse for bots to enter, 
If u are already aware, I wanna know your opinion, Thanks bud

here is a demo I found:- 
https://browserleaks.com/social

**Comment by abrahamjuliot** [comment]
Looks like that [concept](https://robinlinus.github.io/socialmedia-leak/) relies on [3rd party cookies](https://user-images.githubusercontent.com/6946045/178090997-ae445b62-778e-406c-9893-c7796171500e.png). 

I've looked at a few automation tools that offer that functionality. Infinite social media accounts.
Bots can pretty much do anything and everything humans do on the web, except for actually enjoying some good cat videos.

**Comment by vis2021t** [comment]
Clear as cute cats
