### ISSUE TITLE
trust score meaning?

### ISSUE THREAD

**Issue by arthuredelstein** [abrahamjuliot/creepjs#189]
I'm trying to understand the Trust Score. On my machine, Brave gets a 0%, Tor Browser get 84%, and Chrome gets 100%. 

What is the meaning of Trust Score? Does a higher trust score indicate the browser is measured as "more private" or "less private"? Some more info in the documentation or the page would help. Thanks!

**Comment by abrahamjuliot** [comment]
That's a great question. I will add more info to the documentation. It definitely needs improvements.

The trust score shows the level of trust computed from the browser fingerprint. If the score is 100%, there is a high level of trust in the reported values. Values should not be trusted when the score is low. 

No attempt is made to score how well a browser performs against fingerprint traceability and linkability. It is not always beneficial to have a high trust score, and sometimes a low trust score is not bad.

In the prediction section, the crowd blending score is a site indicator that scores how well certain metrics blend in with other fingerprints (strictly collected on the same site). A low trust score can be improved and amended by a high crowd-blending score. Tor Browser, for example, should yield a high crowd-blending score, which results in an increased trust score. 

I hope this helps. Let me know if there are any areas that could use clarity. Your input is greatly appreciated.

**Comment by vis2021t** [comment]
> That's a great question. I will add more info to the documentation. It definitely needs improvements.
> 
> The trust score shows the level of trust computed from the browser fingerprint. If the score is 100%, there is a high level of trust in the reported values. Values should not be trusted when the score is low.
> 
> No attempt is made to score how well a browser performs against fingerprint traceability and linkability. It is not always beneficial to have a high trust score, and sometimes a low trust score is not bad.
> 
> In the prediction section, the crowd blending score is a site indicator that scores how well certain metrics blend in with other fingerprints (strictly collected on the same site). A low trust score can be improved and amended by a high crowd-blending score. Tor Browser, for example, should yield a high crowd-blending score, which results in an increased trust score.
> 
> I hope this helps. Let me know if there are any areas that could use clarity. Your input is greatly appreciated.


clear my doubt but sometimes I feel like It could have been more work needed on the server side but u kept it private as your wish. 

but maybe an alternative design model of server where we community can actually go put work in

**Comment by abrahamjuliot** [comment]
> [server community work]

I will think about it. But, I do want to avoid creating a public server that could be used by bad actors for malicious tracking. Maybe I could expose the core functions only.

**Comment by vis2021t** [comment]
> > [server community work]
> 
> I will think about it. But, I do want to avoid creating a public server that could be used by bad actors for malicious tracking. Maybe I could expose the core functions only.


I agree about that, You are right this can be used for malicious tracking. mm Exposing core function is not something of a gud idea I guess, The best u can provide is a model explanation I guess

**Comment by arthuredelstein** [comment]
Thanks Abraham! The new text helps, but I still have questions. :)

I think it would help if you could add definitions and/or examples for the following things on the README:

* "loose" fingerprint
* shadow bits
* trash
* lies
* errors

Also, it would be great to have more explanation of "'trust' in the reported values". Which values does this refer to (is it fingerprintable API return values, or derived values?), and does trust mean confidence in a statistical sense? If a browser (such as Brave) is adding noise to a particular value, would that reduce the trust value reported here?

Thanks again for this awesome project!

**Comment by abrahamjuliot** [comment]
I'm adding some clarity and adjusting the flow in ... Trust is computed from the browser fingerprint values and revision indicators. Confidence is a good way to put it.

Noise values will significantly reduce the trust score if they differ from the specification (look suspicious) or fail consistency tests. If the noise values are good and consistent with the engine, then they should pass. For example, media devices, web speech, memory, and cores should pass in Brave.

However, on each new session if the noise is renewed, this will trigger the revision indicators and slightly lower the score.

I should note, the above scenario is not necessarily bad, especially if good web traffic on a given site is following the same pattern, and although we can sun categorize this pattern, the entropy is much lower than normal traffic.

**Comment by arthuredelstein** [comment]
Thank you @abrahamjuliot !
