### ISSUE TITLE
Hangs when WebCrypto is unavailable

### ISSUE THREAD

**Issue by lanodan** [abrahamjuliot/creepjs#192]
Setup:
- WebKitGTK 2.36.4 with WebCrypto disabled (compile time)
- creepjs as of 2e51f37b6ecfac651493a19500510cd264a7accb

Console logs:
```
[Log] Fingerprinting complete in 270.00ms (creep.js, line 11433)
[Error] TypeError: undefined is not an object (evaluating 'crypto.subtle.digest') — creep.js:631
promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: Right side of assignment cannot be destructured
(anonymous function) (creep.js:11690)
asyncFunctionResume
(anonymous function)
promiseReactionJobWithoutPromise
promiseReactionJob
```

**Comment by abrahamjuliot** [comment]
Can Web Crypto API be enabled in WebKitGTK 2.36.4? Target browser support is currently in ~2019.

**Comment by abrahamjuliot** [comment]
Closing for now. We do want to avoid hanging promises, but in this case the API is a long-standing web standard.
