### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by liusp217** [abrahamjuliot/creepjs#196]
Excuse me.How do I run it? After I run NPM install and node creep.js, the web reports an error and cannot display fingerprint data.

**Comment by hkaancaliskan** [comment]
![Screenshot_20220805-172105_Firefox Nightly](https://user-images.githubusercontent.com/17825767/183096818-074d4b6f-6f87-4b60-a0cb-b732e9152c60.png)

Idk why but i got this error for 2 days, do you mean this error?

**Comment by abrahamjuliot** [comment]
Hey @liusp217 and @hkaancaliskan 

So, these might be 2 different errors. The `TypeError` should be fixed now. 

I'm adding a quick start [here](https://github.com/abrahamjuliot/creepjs#develop) and more info on the fingerprinting API [here](https://github.com/abrahamjuliot/creepjs#fingerprinting-api).

I will leave this issue open for a bit in case you have any questions.

Thank you both for reporting the issues.
