### ISSUE TITLE
Uncaught TypeError on latest version of Bromite (v105)

### ISSUE THREAD

**Issue by uazo** [abrahamjuliot/creepjs#202]
I am getting this error with the latest (v105) version of [Bromite](https://github.com/bromite/bromite):

```
Uncaught TypeError: cv[TW(...)][TW(...)] is not a function
    at cx.<computed> (creep.js:formatted:2618:50)
```

![image](https://user-images.githubusercontent.com/29201891/191684430-6348cdb4-75cf-43c2-a648-ba0a59540d05.png)

I'm available if you need some additional tests

**Comment by abrahamjuliot** [comment]
Hey @uazo, thank you for reporting this. My error. Forgot to check the `getChannelData` support when I added a new analysis. It should be fixed now in e2b4f25.
