### ISSUE TITLE
Way to self host API?

### ISSUE THREAD

**Issue by philosofonusus** [abrahamjuliot/creepjs#203]
As a student has been doing a research project. It is a big data project, maybe there is a way to self host it?

**Comment by abrahamjuliot** [comment]
I am not sure if I understand the question. Are you looking to host your own API for your project?

**Comment by philosofonusus** [comment]
> I am not sure if I understand the question. Are you looking to host your own API for your project?

Yes

**Comment by abrahamjuliot** [comment]
This repo might catch your interest ([here](https://github.com/awesome-selfhosted/awesome-selfhosted)). There is a lot there. Have a look at the [misc section](https://github.com/awesome-selfhosted/awesome-selfhosted#miscellaneous).

https://databunker.org looks nice
