### ISSUE TITLE
Puppeteer Extra Undetected with Page Obtained by browser.pages()

### ISSUE THREAD

**Issue by naumanzchaudhry** [abrahamjuliot/creepjs#208]
Hi, thanks for this awesome project. Seems like if we change the way we obtain the `Page` instance. Extension doesn't get detected under `Resistance`

**Not Detected**
```
 const [page] = browser.pages()
```
**Detected**
```
const page = brower.newPage()
```

**Setup**

```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const stealth = StealthPlugin();
puppeteer.use(stealth);

const HEADLESS = false;

puppeteer
  .launch({
    headless: HEADLESS,
  })
  .then(async (browser) => {
    
    // comment one of the following 2 lines at a time & check the result under resistance
    const [page] = await browser.pages();
    const page = await browser.newPage();
    
    await page.goto('https://abrahamjuliot.github.io/creepjs/');
  });
```

**Comment by abrahamjuliot** [comment]
Nice find. Thank you for reporting. I will take a look.

**Comment by naumanzchaudhry** [comment]
**Update**

For `browser.pages()` call, `hardwareConcurrency` hash is different from that of `newPage()` call.

This [condition here](https://github.com/abrahamjuliot/creepjs/blob/01a6bfc3e3575e014f46be100cb1814904154e95/src/resistance/index.ts#L450) is failing that's why it's not reporting it to be `puppeteer-extra`.

with `browser.pages()` the hash is `55e9b959` which isn't in the hardwareConcurrency hashes array of puppeteerExtra

@abrahamjuliot

**Comment by naumanzchaudhry** [comment]
**Update # 2**

`lies` when `browser.pages()`

<img width="383" alt="pages-lies" src="https://user-images.githubusercontent.com/15146710/209158291-29b542ab-ca40-4fc0-aaaf-aee3d22a01aa.png">

`lies` when `browser.newPage()`

<img width="461" alt="newPage-lies" src="https://user-images.githubusercontent.com/15146710/209158412-8d9d765a-0743-4e92-835c-7d746ad4b10e.png">

**Comment by naumanzchaudhry** [comment]
**Update # 3**

This [call](https://github.com/abrahamjuliot/creepjs/blob/243068a4c766c3dc698dac43eeaf642448479b62/src/lies/index.ts#L232) for creating proxy on `hardwareConcurrency` has following results
```
browser.pages -> false
browser.newPage -> true
```

**Comment by abrahamjuliot** [comment]
I was unable to reproduce. `const [page] = await browser.pages()` applies no evasions for me. However, I'm adding `55e9b959` as a hash for `hardwareConcurrency`. It should release shortly. Hopefully, that improves the detection.

**Comment by naumanzchaudhry** [comment]
@abrahamjuliot thanks for your time.

1. For me, it's not detecting the `puppeteer-extra` as can be seen in this [screencast] (even with the latest update) (https://drive.google.com/file/d/1B9yj7Tu885OccpFU_jjItIlA96Pg0ROO/view?usp=sharing)

2. Interestingly, this isn't working for me even with the latest update, because for some reason, the `hash` is now different. Now the `hash` showing up is `c767712b` which is something called [disabled ](https://github.com/abrahamjuliot/creepjs/blob/67325b159cc1473268fc2abe895fd89f68146fe0/src/resistance/index.ts#L140)

**Comment by naumanzchaudhry** [comment]
@abrahamjuliot so basically you mean that with `browser.pages()` extra stealth plugin doesn't apply any evasions?

**Comment by abrahamjuliot** [comment]
Yes
