### ISSUE TITLE
Add Browserless Plugin Detection Support

### ISSUE THREAD

**Issue by iambilalriaz** [abrahamjuliot/creepjs#210]

**Comment by abrahamjuliot** [comment]
Do you have a specific plugin in mind?

**Comment by iambilalriaz** [comment]
@abrahamjuliot - https://github.com/browserless/chrome

**Comment by abrahamjuliot** [comment]
Taking a closer look at this just now. It's a connection service. The browser I connected to was Chrome 102 on Linux, so there is that. However, by all appearances it is a clean browser, so nothing can be detected. 

If features were missing or modified, we could possibly find a stable pattern to fingerprint, but it looks clean.

**Comment by abrahamjuliot** [comment]
Closing for now, but let's re-visit with other tools.
