### ISSUE TITLE
Plans for a lightweight deployable version

### ISSUE THREAD

**Issue by gitgitwhat** [abrahamjuliot/creepjs#211]
Great library but I'm struggling with how to implement it into my site.  Do you have plans to make a lighter-weight deployable version that just has some simple APIs like `isBot()` or `getTrustScore()` and doesn't require external calls or generating UI output?

**Comment by abrahamjuliot** [comment]
Hey, that's a great question. 

We want to avoid creating a library for fingerprinting. The main goal is to promote research and education about browser fingerprinting. No plans to change this.
