### ISSUE TITLE
Is there a way to use it in a static page without a front framework?

### ISSUE THREAD

**Issue by DongJu-Na** [abrahamjuliot/creepjs#215]
I am currently using thymeleaf without using front framework.
Is there a way to use it in a static page without a front framework?

**Comment by DongJu-Na** [comment]
An error occurs at build time. Could you please provide a bundle?
I want to study this project. 😭

**Comment by DongJu-Na** [comment]
It resolved itself and closed this issue.

**Comment by abrahamjuliot** [comment]
Glad it worked. I'm here if you need help.
