### ISSUE TITLE
api how to use?? help!!! 😫

### ISSUE THREAD

**Issue by DongJu-Na** [abrahamjuliot/creepjs#216]
Can I use https://creepjs-api.web.app/fp api in my development environment other than https://abrahamjuliot.github.io/creepjs/ url?

**Comment by abrahamjuliot** [comment]
Negative, it's locked down. However, you can swap out the URLs and send requests to your server environment.

**Comment by DongJu-Na** [comment]
Could you please explain in more detail?

**Comment by DongJu-Na** [comment]
Can you elaborate on the process of creating an FP ID?
I want to make a fingerprint without looking at the useragent. While specifying which device

**Comment by abrahamjuliot** [comment]
Sure, Fingerprint ID is a hash of browser, engine, platform, and hardware features reported by the browser. Fingerprints can be generated in a raw form or hash identifier, or both. 

Raw values are great for server-side analysis. Hash identifiers are useful for snapshot history and grouping patterns.

There are many techniques, but I recommend starting out simple and fast. Give this [lite fingerprint script](https://www.typescriptlang.org/play?ssl=46&ssc=47&pln=1&pc=1#code/GYVwdgxgLglg9mABAcwKZQBIEMDOALACgA8AuRcAazDgHcwBKRAbwChF3EIEcpEArHAkQBeRACkAygHkAcgDoeAJxhhkMYAE9i9FgEguYHojy48I-oLBsONhQAcANjCgEA5K503bi1ABMQEKgEBCb4ADSIAPoRMIzCAHyIALJYUHhyMAC2IA4EAMwAjBGheIwA1BYIchAmigDCcL6oAIIusYgAPogADBHdRAAcBQUQAJy+EACsOro+UCCKSG7dK6vdrogVIaaI8Xs99HJQcBJQyqoEBQBs9Ic4IABGSgQAtAM6AL4sLKCQsEJoKAAGWcqAAYio0Io7OcXIxWDYDEYmIgaDBfGliqgYMg8FAIlgAG5YGAOADq6MxiCJJIcGGxuN4H3MOAgPlQSAA9JzEFIJJyAKKqFSoRASNmoDnWdhI3gIrzsbmIAACUBwL1QRDsqGgGsUijginIYCawBFvkQ6kQ1F49zsdkNUD80q8TUJMECSVQmUNGgiSq9PsUGhdNlqvhoWB8DUgCx8kD9iCVDR8OFDHEyWCIABU4AE8AAFOAqNX+nm5-Pp9iOVLAQ2ZMu8iRVxAOLCqEBYNCNoHt5CIAs+YCoeOBRAttsdruoHA9vvJOBGQeoYf6502ZmiMBEnGpQ0u2XMRCwTKoABaCFQEQccAgWAcos3iAAkmAoA45AARVKobNZcH1qkBCHKmcAOISfhSHY-yGMBSY8nygrCmAop-qeABel7UiaiC9lOaAHtwvAPAaNA4COzQmnUTgclAYKoKkCwzuYUgPHwOpQHIgJSHQg5wNqihQBoMhYKeOAEGiJq0PQADcLounMCxIAA2i2aIYngYQtngDJ4lpCrsDSpIUhp+kGUZdK6fiLZuh6qAFjARCoA4ABKqTwGZCq2Z63q+p5XjhpG0YIBAcYchAfotpmOZ5jURYlrOLY1lAdaKA2UWpDUXq+DAWBuAQMIriO6pcDeigvKyOmniQTiMvQHhyJmUA1DOjYNGVA5DiO4WoBlzV4NluX5YVq7qj4-iBL4Lw+jBJDjQEqD1YcTUtbO8GIJRWTuUIy6rj1LYnuel7+TYN53g+J0cJOyCdt2E59rdrUtiRtDkYolG+NRMC0fRjGpv5AC6LBfIePBRrwogCalmaQKgcjUDQwEsIeqY5BDKDoCCToQqoI4wiWSNImBcMQA+UaE9wxNyDeyAEAABlwmSOOgqBkAAJEwBUjtD7aBPDtBwS8iBg4JhzHBCTm+AQABM9AfJkOB0zoRMPtTcC03TZq49CsLs0wgLYPgBCow4UBy0rQA) a try. It runs in under `5ms`.

```js
function getHash(x: unknown) {
    const json = JSON.stringify(x)
	const hash = json
        .split('')
        .reduce((hash, _, i) => Math.imul(31, hash) + json.charCodeAt(i) | 0, 0x811c9dc5)
	return ('0000000' + (hash >>> 0).toString(16)).substr(-8)
}

function getLiteFingerprint() {
    const { width, height, availWidth, availHeight } = screen // OS/Engine Screen
    const {
        deviceMemory, // Memory
        hardwareConcurrency, // Cores
        maxTouchPoints, // Touch
        platform, // OS
        language, // Lang Preference 
        languages, // Lang Most Preferred
    } = navigator
    const { timeZone, locale } = Intl.DateTimeFormat().resolvedOptions() // OS/Engine Timezone and Language
    const browserAndClientFeatures = Object.getOwnPropertyNames(window); // Browser Release and Client Features
    
    return [
        width,
        height,
        availWidth,
        availHeight,
        devicePixelRatio,
        deviceMemory,
        hardwareConcurrency,
        maxTouchPoints,
        platform,
        matchMedia('(prefers-color-scheme:light)').matches, // Color Preference
        matchMedia('(prefers-reduced-motion:reduce)').matches, // Animation Preference
        timeZone,
        locale,
        language,
        languages,
        browserAndClientFeatures,
    ]
}
const start = performance.now()
const result = getLiteFingerprint()
console.clear()
console.log(`complete: ${(performance.now() - start).toFixed(2)}ms`)
console.log(`fingerprint: ${getHash(result)}`)
```

**Comment by DongJu-Na** [comment]
Thank you  😁 very much for your detailed answer.

However, it is not the result I want.
Every time I run the code you have guided me to
Strings are changing.

ex)
"fingerprint: afe25423"
"fingerprint: 6b722854"

The conditions I need to meet are as follows.
============
1) The only key that can be specified by any browser

2) Do not allow duplication

=============

So I created sophisticated creepjs with typescript.
After building with yarn, converting to javascript, removing useragent and api, and checking in the local environment. I am having difficulty removing useragent items during this process.

We're analyzing well-written code after the build.

**Comment by abrahamjuliot** [comment]
> Strings are changing.

Try commenting out the `browserAndClientFeatures` value or hash it separately. If you have extensions installed on your browser, such as DuckDuckGo, some store random properties on the window object. 

> difficulty removing useragent 

User agent items are mostly in worker and navigator files.

**Comment by DongJu-Na** [comment]
Thank you so much for your help. I will proceed as you said on March 30th. Thank you!! I will continue to analyze the code :)

**Comment by DongJu-Na** [comment]
Closed issue as it didn't solve the problem.

What I was trying to do was a way to specify using fingerprints on mobile devices even if the browser is different.
Fingerprints seem to have limitations.

Thanks for your help. 😋

**Comment by abrahamjuliot** [comment]
For Chrome, you can get the number of bytes allocated to the site for storage. That's over 128 Billion possible fingerprints on a 120 GB device. Not many limitations there.

**Comment by abrahamjuliot** [comment]
Chrome on Android provides a significant amount of entropy. You can get the exact device model and network condition (Wi-Fi, Ethernet, etc.). Moreover, on mobile, the device pixel ratio and screen resolution combined can hint to the device model for all browsers.

**Comment by abrahamjuliot** [comment]
The other factor to consider is the context fingerprinting occurs. A fingerprint on site A can be more unique to a user than it is on site B.

**Comment by DongJu-Na** [comment]
me and my friend
Assuming that the device model is the same and all settings are the same
Is it possible to distinguish me from my friends using fingerprints?

ex)
                                    me               friend 
phonemodel              phone1        phone1
fingerfirnt(chrome)         aaaa   bbbb
fingerfrint(edge)             aaaa   bbbb
fingerfrint(safari)            aaaa   bbbb

When I analyzed the creep.js source, it seems impossible..

**Comment by abrahamjuliot** [comment]
If you purchase 2 matching devices, use the same SD card, same time zone/language, same OS preferences, same browser and release, same settings/permission, same network, and don't modify storage, the fingerprints can match.

CreepJS does not showcase or even attempt more advanced techniques. There is also code that is used for analysis and does not get factored into the fingerprint, and there are also behavioral patterns not implemented here. Combine that with site-specific events, and it becomes more possible to distinguish matching browsers.

**Comment by DongJu-Na** [comment]
thanks for the answer 😊
