### ISSUE TITLE
Bug in creep.ts

### ISSUE THREAD

**Issue by rdeets** [abrahamjuliot/creepjs#222]
Line 250 should be changed from this:
const { anyPointer } = cssMediaComputed || {}

To something like this? 
const { 'any-pointer': anyPointer } = cssMediaComputed?.mediaCSS || {}

**Comment by rdeets** [comment]
Also in navigator.ts getBluetoothAvailability function

`navigator.bluetooth.getAvailability() `
returns a promise and should be something like: 
`return navigator.bluetooth.getAvailability().then((available: boolean) => available)`

**Comment by abrahamjuliot** [comment]
Nice catch. I added c17490f for the next renewal.
