### ISSUE TITLE
Where is the known data to determine LowerEntropy?

### ISSUE THREAD

**Issue by ginlink** [abrahamjuliot/creepjs#223]
Hello, I've read some of the source code, but I don't really understand LowerEntropy. Where is the known data to determine LowerEntropy? Public? or self-collected?

**Comment by abrahamjuliot** [comment]
It's based on the site's weekly history. The source data is private, but everything confirmed as normal is public. 

The best way to generate low entropy fingerprints is to let the site traffic determine what is normal. It will be different depending on the context and type of traffic.

**Comment by abrahamjuliot** [comment]
`LowerEntropy` is used as a firewall to only allow what is acceptable and safe to consume. If the entropy is too high or unsafe to digest, we lower it or instantly block it.

**Comment by ginlink** [comment]
> `LowerEntropy` is used as a firewall to only allow what is acceptable and safe to consume. If the entropy is too high or unsafe to digest, we lower it or instantly block it.

Thanks for your reply, I get it now 😊. 
I will close the question.
