### ISSUE TITLE
400::API access denied if i use  --disable-web-security switch for chromium

### ISSUE THREAD

**Issue by NCLnclNCL** [abrahamjuliot/creepjs#227]
did you block if i use this

**Comment by ginlink** [comment]
+1

**Comment by ginlink** [comment]
it's work now 😄

**Comment by NCLnclNCL** [comment]
> it's work now 😄

dont work

**Comment by abrahamjuliot** [comment]
It is likely that the network you are on is too hot and will have a higher token cost per request. Let me know if it's something else, maybe related to issue [213](https://github.com/abrahamjuliot/creepjs/issues/213).

**Comment by abrahamjuliot** [comment]
Closing for now, but let me know the issue continues.
