### ISSUE TITLE
Doubts about the erro infos

### ISSUE THREAD

**Issue by AsaphF** [abrahamjuliot/creepjs#242]
I am changing the navigator.deviceMemory using Silenium, and the value is indeed changed but the erros pop up.
It appears :

 Navigator.deviceMemory:
failed undefined properties

Why this happens ?

(I read your article about tampering, it is possible to use the estrategies in this function ?
Article : https://adtechmadness.wordpress.com/2019/03/23/javascript-tampering-detection-and-stealth/

Thank you, yours articles is helping me a lot.
)

**Comment by abrahamjuliot** [comment]
Special thanks to adtechmadness for the article. I'm just a fan of the blog.

JS evasions cause glowing leaks in the native code. As outlined in the article, patching them is possible and that can cause more leaks. The use of a Proxy is a technique described. It has some less obvious leaks.

**Comment by AsaphF** [comment]
I see, thank you about your awnser,  and why the value is changed this error appears : Navigator.deviceMemory:
failed undefined properties

**Comment by abrahamjuliot** [comment]
This should return `undefined`.
```js
Object.getOwnPropertyDescriptor(navigator, 'deviceMemory')
```

If we do something like this, the above no longer returns `undefined`
```js
Object.defineProperty(navigator, 'deviceMemory', { value: 4 })
```

**Comment by AsaphF** [comment]
Object.defineProperty(navigator, 'deviceMemory', { value: 4 })

I am making exactly this and its returnig undefined.

**Comment by abrahamjuliot** [comment]
Can you share your code?

**Comment by AsaphF** [comment]
Yes i can.

Here :

`
js_code = f"""
                Object.defineProperty(navigator, 'deviceMemory', {{ "get": () => 4 }}); 
            """
            driver = uc.Chrome(options=options)
            driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {"source": js_code})
`

**Comment by abrahamjuliot** [comment]
Here it is. If we run `Object.getOwnPropertyDescriptor` like so, it correctly returns undefined. If we apply the change and run it again, it fails. It should always return undefined with those arguments.

![image](https://github.com/abrahamjuliot/creepjs/assets/6946045/dd9ea4d3-b4c4-49ff-b311-21cf2b88523a)

**Comment by AsaphF** [comment]
Pardon me, i did not realize that were a diferent method.
Thank you very much.

**Comment by abrahamjuliot** [comment]
It's all good. I'm here if you encounter any issues.
