### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by aniketbeez** [abrahamjuliot/creepjs#248]
Hi, 

I notice that requests to https://creepjs-api.web.app/fp api are locked out. Is there any alternate way to generate the device fingerprint in our development environment ?

**Comment by abrahamjuliot** [comment]
Github Codespaces should work, but let me know if that does not work.

**Comment by abrahamjuliot** [comment]
I'll double-check this weekend. I think the URL was updated for Codespaces and needs to be accepted.

**Comment by abrahamjuliot** [comment]
That is correct.

There are services on the web for these purposes. I have none to recommend.

**Comment by TRHX** [comment]
I started CreepJS using Github Codespaces, but https://creepjs-api.web.app/fp The request is still blocked.

https://supreme-goggles-7rg647p6xj73xwrv-8000.app.github.dev/

**Comment by abrahamjuliot** [comment]
This should be fixed now. But, let me know if you encounter any issues.
