### ISSUE TITLE
lazy loading iframes

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [abrahamjuliot/creepjs#250]
links
- https://bugzilla.mozilla.org/show_bug.cgi?id=1622090#c20 Release notes
   - emphasis mine
   - > Lazy loading iframes are **_only loaded when visible_**
- https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading
- https://bugzilla.mozilla.org/show_bug.cgi?id=1860729 enable for release at this stage in FF121

abraham, is this sort of thing going to affect some of our tests (I think you use iframes more than me) - the "visible" part is concerning. I haven't seen any adverse effects (e.g. in TZP), but I've only been back for a couple of days (was AFK for 11 days, getting a suntan in Sweden)

**Comment by abrahamjuliot** [comment]
I might only affect iframes that have a URL to load, but I will take a closer look at this. As far as I know, the element is rendered immediately, but the document requires the load event.

**Comment by Thorin-Oakenpants** [comment]
I don't render anything in mine - but I know you like to shove crap in yours :)

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1860729#c5 (emphasis mine)
> Lazy loading iframes are now supported **_`(<iframe loading=lazy>)`_** 

so I guess this isn't something we need worry directly about
