### ISSUE TITLE
Firefox trash after update

### ISSUE THREAD

**Issue by ferenc-a** [abrahamjuliot/creepjs#253]
There's a new trash entry detected for me on the latest Firefox that wasn't there before.
I'm on Firefox 119 now, and checked that I had 0 trash in Firefox 114.
This is the message: `1: CanvasRenderingContext2D.getImageData: suspicious pixel data`
![image](https://github.com/abrahamjuliot/creepjs/assets/140697579/03713830-57cf-43de-9570-5a8fd6e257a4)
I'm on Windows btw,

**Comment by abrahamjuliot** [comment]
I'll take a look and aim to clear it.

**Comment by abrahamjuliot** [comment]
This should be resolved and live, but let me know if you encounter any issues.
- https://github.com/abrahamjuliot/creepjs/pull/255
