### ISSUE TITLE
CSP blocking worker

### ISSUE THREAD

**Issue by Afro27** [abrahamjuliot/creepjs#268]
Content-Security-Policy is blocking the use of workers on the site i wanna use creepjs. Is there a way to make the script work without workers? The output or quality of fingerprinting would be affected?

**Comment by abrahamjuliot** [comment]
I do not recommend running it modified or outside the GitHub source. However, it is possible to skip the `spawnWorker` call and conduct experiments. Everything here is educational, not intended for legitimate sites.

**Comment by abrahamjuliot** [comment]
Closing for now, but please don't hesitate to re-open if you have any questions.
