### ISSUE TITLE
Creepjs trust score: 75% C+ in hidemium?

### ISSUE THREAD

**Issue by edersion9937111** [abrahamjuliot/creepjs#272]
![image](https://github.com/user-attachments/assets/0944c633-6505-41d2-9bda-eed2a32084f3)

![image](https://github.com/user-attachments/assets/10962ce1-781e-4962-a2c6-bd2086ebb925)

Bypass trust score: 75% in hidemium.io
How can I do this in my real browser?

**Comment by abrahamjuliot** [comment]
Yep, not advised. Closing...
