### ISSUE TITLE
 Is there any problem with time zone detection?

### ISSUE THREAD

**Issue by cbgz121** [abrahamjuliot/creepjs#275]
Why is this device of timezong normal only when my time zone and language are only China-Chinese or American-English, but for example, if my time zone is Malaysia and the language is Malay, it will turn red？please
![chrome_N5vazuSk6L](https://github.com/user-attachments/assets/6de769ab-b1e9-4e92-bea9-a8c56b275851)
![chrome_XZVOR090g8](https://github.com/user-attachments/assets/67cc0deb-fc96-413e-9c73-1f395dfe968c)
![chrome_MasmZaniT7](https://github.com/user-attachments/assets/cc7509c1-2c3e-4f88-9d96-b4cb9fb31e5a)
![chrome_ZNzaz3iMwl](https://github.com/user-attachments/assets/52f09351-9760-4e8b-97be-b82a95f50c57)

**Comment by abrahamjuliot** [comment]
Red just means we have no historical snapshots of the entropy on the site, and it's either new visitors or requiring further looking at. It means neither good nor bad. I'll update the snapshots soon, but I usually keep them static for a year or two. It gives a better idea of what changes overtime.

**Comment by abrahamjuliot** [comment]
My device is always red 😅

**Comment by cbgz121** [comment]
Okay, thank you. I have another question. If it is red, the crowdBlendingScore will be very low, which will lower the total score. This seems a bit unreasonable.

**Comment by cbgz121** [comment]
Okay, thank you. I have another question. If it is red, the crowdBlendingScore will be very low, which will lower the total score. This seems a bit unreasonable.

**Comment by abrahamjuliot** [comment]
The score, whether high or low, just means that the entropy can be distinguished. Intent is not considered and It's really not necessary to convey it in the form of a score.

**Comment by abrahamjuliot** [comment]
Closing for now. Re-opens are welcome.
