### ISSUE TITLE
Collect resources

### ISSUE THREAD

**Issue by abrahamjuliot** [abrahamjuliot/creepjs#52]
# Papers
- [Carnus: Exploring the Privacy Threats of Browser Extension Fingerprinting](https://www.ndss-symposium.org/wp-content/uploads/2020/02/24383.pdf) (Karami et al., 2020)
- [Shedding light on web privacy impact assessment: A case study of the Ambient Light Sensor API](https://lukaszolejnik.com/SheddingLightWebPrivacyImpactAssessmentIWPE20.pdf) (Olejnik, 2020)
- [Fingerprinting the Fingerprinters: Learning to Detect Browser Fingerprinting Behaviors](https://umariqbal.com/papers/fpinspector-sp2021.pdf) (Iqbal et al., 2020)
- [Taming The Shape Shifter: Detecting Anti-fingerprinting Browsers](https://hal.archives-ouvertes.fr/hal-02612461/document) (Laperdrix et al., 2020)
- [Long-Term Observation on Browser Fingerprinting: Users’ Trackability and Perspective](https://petsymposium.org/2020/files/papers/issue2/popets-2020-0041.pdf) (Pugliese et al., 2020)
- [Robust Website Fingerprinting Through the Cache Occupancy Channel](https://arxiv.org/pdf/1811.07153.pdf) (Shusterman et al., 2019)
- [Browser Fingerprinting: A survey](https://arxiv.org/pdf/1905.01051.pdf) (Laperdrix et al., 2019)
- [Evaluating Anti-Fingerprinting Privacy Enhancing Technologies](https://www1.icsi.berkeley.edu/~mct/pubs/www18.pdf) (Tschantz et al., 2019)
- [Clock Around the Clock: Time-Based Device Fingerprinting](http://www.eurecom.fr/fr/publication/5664/download/sec-publi-5664.pdf) (Sanchez-Rola et al., 2018)
- [On Estimating Platforms of Web User with JavaScript Math Object](https://meiji.elsevierpure.com/en/publications/on-estimating-platforms-of-web-user-with-javascript-math-object) [[google](https://www.google.com/books/edition/_/4-xqDwAAQBAJ?hl=en&gbpv=1&pg=407)] (Saito et al., 2018)
- [FP-STALKER: Tracking Browser Fingerprint Evolutions](https://hal.inria.fr/hal-01652021/document) (Laperdrix et al., 2017)
- [Inhibiting Browser Fingerprinting and Tracking](https://eprints.soton.ac.uk/408726/1/possible_to_tackle_fingerprinting_complete2.pdf) (Luangmaneerote et al., 2017)
- [FPGuard: Detection and Prevention of Browser Fingerprinting](https://www.researchgate.net/publication/300781053_FPGuard_Detection_and_Prevention_of_Browser_Fingerprinting) (Weldemariam et al., 2015)
- [Fingerprinting web users through font metrics](https://fc15.ifca.ai/preproceedings/paper_83.pdf) (Fifield et al., 2015)
- [PriVaricator: Deceiving Fingerprinters with Little White Lies](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr1-1.pdf) (Nikiforakis et al., 2014)
- [The Web Never Forgets: Persistent Tracking Mechanisms in the Wild](https://securehomes.esat.kuleuven.be/~gacar/persistent/the_web_never_forgets.pdf) (Englehardt, et al., 2014)
- [Cookieless Monster: Exploring the Ecosystem of Web-based Device Fingerprinting](https://sites.cs.ucsb.edu/~vigna/publications/2013_SP_cookieless.pdf) (Nikiforakis et al., 2013)
- [Reducing the value of a browser fingerprint](https://www.researchgate.net/publication/302695509_Reducing_the_value_of_a_browser_fingerprint) (Jenkins et al., 2013)
- [Pixel Perfect: Fingerprinting Canvas in HTML5](https://hovav.net/ucsd/dist/canvas.pdf) (Mowery et al., 2012)

# Articles
- [Shedding light on designing web features with privacy: risks, impact assessments, case study](https://blog.lukaszolejnik.com/shedding-light-on-designing-web-features-with-privacy-risks-impact-assessments-case-study/) (Olejnik, 2020)
- [Detecting Privacy Badger’s Canvas FP detection](https://adtechmadness.wordpress.com/2020/03/27/detecting-privacy-badgers-canvas-fp-detection/) (Adtech Madness, 2020)
- [JavaScript tampering – detection and stealth](https://adtechmadness.wordpress.com/2019/03/23/javascript-tampering-detection-and-stealth/) (Adtech Madness, 2019)
- [Bot detection 101 #3 – Cheating browser fingerprinting](https://adtechmadness.wordpress.com/2019/03/11/bot-detection-101-3-cheating-browser-fingerprinting/) (Adtech Madness, 2019)
- [Bot detection 101 #2 – Entering browser fingerprinting](https://adtechmadness.wordpress.com/2019/03/05/bot-detection-101-2-entering-browser-fingerprinting/) (Adtech Madness, 2019)
- [Bot detection 101 #1 – Preface](https://adtechmadness.wordpress.com/2019/03/04/bot-detection-101-1-preface/) (Adtech Madness, 2019)

# Talks
- [Exploring the Privacy Threats of Browser Extension Fingerprinting](https://www.youtube.com/watch?v=mfmAWRzpbCU) (Soroush Karami,, 2020)
- [Fingerprinting the Fingerprinters: Learning to Detect Browser Fingerprinting Behaviors](https://www.youtube.com/watch?v=bsgTYQyaPG4) (Umar Iqbal, 2020)
- [Automated Methods for Fingerprinting Detection](https://www.youtube.com/watch?v=qFWPTeDSJn4) (Sarah Bird, 2019)
- [Next Steps For Browser Privacy: Pursuing Privacy Protections Beyond Extensions](https://www.youtube.com/watch?v=odtcH6UmkbU) (Peter Snyder, 2019)
- [Privacy, Standards, and Anti-Standards](https://www.youtube.com/watch?v=xxk9UKulC1c) (Peter Snyder, 2019)
- [Fingerprinting and Privacy on the Web](https://www.youtube.com/watch?v=OVh0oHbmla0) (Peter Snyder, 2019)
- [Browser fingerprinting: past, present and possible future](https://www.youtube.com/watch?v=PLVJ5yQb0vc) (Pierre Laperdrix, 2019)
- [Tales From the Trenches: Fingerprints on the Web - Igor Trindade Oliveira](https://www.youtube.com/watch?v=hZg0Ks_IHjQ) (Igor Trindade Oliveira , 2018)
- [Fp-Scanner: The Privacy Implications of Browser Fingerprint Inconsistencies](https://www.youtube.com/watch?v=n-kN0Ys4yNM) (Antoine Vastel, 2018)
- [Tracking Browser Fingerprint Evolutions](https://www.youtube.com/watch?v=xNwfdsu4ZKE) (Antoine Vastel, 2018)
- [Navigating the Vast Ocean of Browser Fingerprints](https://www.youtube.com/watch?v=VUsTdf8r_m4) (Russell Thomas, 2018)
- [(Cross-)Browser Fingerprinting via OS and Hardware Level Features](https://www.youtube.com/watch?v=piftpgsZE9g) (Yinzhi Cao, 2017)
- [Beauty and the Beast: Diverting modern web browsers to build unique browser fingerprints](https://www.youtube.com/watch?v=p0doExrQwY0) (Pierre Laperdrix, 2016)
- [Panopticlick: Fingerprinting Your Web Presence](https://www.youtube.com/watch?v=3xQLy6lH5OE) (Bill Budington, 2016)
- [Everything you always wanted to know about web-based device fingerprinting (but were afraid to ask)](https://www.youtube.com/watch?v=5Y1Y96jC5AA) (Nick Nikiforakis, 2016)
- [Advanced Browser Fingerprinting](https://www.youtube.com/watch?v=kk2GkZv6Wjs) (Yan Zhu, 2015)
- [Website Fingerprinting Attacks and Defenses](https://www.youtube.com/watch?v=RJyQFaQsyz0) (Rob Johnson, 2014)
- [Web Fingerprinting: How, Who, and Why?](https://www.youtube.com/watch?v=aSfh0efL7rs) (Nick Nikiforakis, 2013)

# Researchers
- https://antoinevastel.com (Antoine Vastel)
- https://plaperdr.github.io (Pierre Laperdrix)
- https://www.peteresnyder.com (Peter Snyder)
- https://lukaszolejnik.com (Lukasz Olejnik)
- https://www.securitee.org (Nick Nikiforakis)
- https://senglehardt.com (Steven Englehardt)

# Test Sites
- https://arkenfox.github.io/TZP/tzp.html
- https://privacycheck.sec.lrz.de/
- https://canvasblocker.kkapsner.de/test/

# Test Suites
- https://www.lambdatest.com
- https://www.browserstack.com
- https://kobiton.com
- https://www.browserling.com
- https://crossbrowsertesting.com/
- https://saucelabs.com

# Stats
- https://developers.whatismybrowser.com/
- https://www.primegrid.com/gpu_list.php
- https://gs.statcounter.com/screen-resolution-stats
- https://arh.antoinevastel.com/reports/stats/menu.html

# API Documentation
- https://docs.w3cub.com/dom
- https://developer.mozilla.org

**Comment by abrahamjuliot** [comment]
use js to detect and omit broken links

**Comment by Thorin-Oakenpants** [comment]
https://arxiv.org/pdf/1811.07153.pdf wasn't in my collection

**Comment by abrahamjuliot** [comment]
Sweet! Added it

**Comment by Thorin-Oakenpants** [comment]
here's what a top moz sec dev said about it to me in Dec 2018
> This one kind of sucks. There are no reasonable countermeasures. Page coloring looked interesting, but AFAICT that was
an idea from the early 2000s that hasn't been revisited?
> 
> The 100ms resolution helps; but it isn't the complete answer (and I want to reduce it anyway if we can achieve the same security boundary using fuzzyfox.)
> 
> Maybe the answer is something more complicated? Degrading it dynamically (throttling) if we detect repeated calls and throw a permission prompt (with or without the doorhanger)?

**Comment by Thorin-Oakenpants** [comment]
2020: https://lukaszolejnik.com/SheddingLightWebPrivacyImpactAssessmentIWPE20.pdf
blog: https://blog.lukaszolejnik.com/shedding-light-on-designing-web-features-with-privacy-risks-impact-assessments-case-study/

**Comment by Thorin-Oakenpants** [comment]
[2018 - Clock Around the Clock - 10.1145-3243734.3243796.pdf](http://www.eurecom.fr/fr/publication/5664/download/sec-publi-5664.pdf)

**Comment by abrahamjuliot** [comment]
I moved this to a repo. Feel free to join and update. I plan to add small code samples too.
