### ISSUE TITLE
get call stack limit

### ISSUE THREAD

**Issue by abrahamjuliot** [abrahamjuliot/creepjs#88]
https://stackoverflow.com/questions/7826992/browser-javascript-stack-size-limit
```js
getMaxCallStackSize = () => {
    try {
        return 1+getMaxCallStackSize()
    } catch (e) { return 1 }
}
;[...Array(10)].forEach(() => getMaxCallStackSize ())
console.log(`${(getMaxCallStackSize ()/1000).toFixed(0)}K`)

```

**Comment by Thorin-Oakenpants** [comment]
hmmmm

**Comment by abrahamjuliot** [comment]
That JIT comment is very interseting. I was not aware this.

10 is just an arbitrary number to catch the max, but I could probably get by with just 4 calls for the function I'm using. Some builds yield higher calls (50-400% more) by the 4th call. The absence of variables also increases the size ([in V8 atleast](https://2ality.com/2014/04/call-stack-size.html))

On Android, Chrome and FF are occasionally unstable even at 10, so I've added rounding: `(getMaxCallStackSize()/100).toFixed(0)*100`

**Comment by kaliiiiiiiiii** [comment]
Found some interesting code about that on [nowsecure.nl](https://nowsecure.nl) (protected by cloudfare) inside a service worker:
```js
onmessage = function(e) {var gsb = function(){
    var sizeA = 0;
    var sizeB = 0;
    var counter = 0;
    try {
        var fn_1 = function () {
            counter += 1;
            fn_1();
        };
        fn_1();
    }
    catch (_a) {
        sizeA = counter;
        try {
            counter = 0;
            var fn_2 = function () {
                var local = 1;
                counter += local;
                fn_2();
            };
            fn_2();
        }
        catch (_b) {
            sizeB = counter;
        }
    }
    var bytes = (sizeB * 8) / (sizeA - sizeB);
    return [sizeA, sizeB, bytes];
}; postMessage({a3: gsb()})};
```
conclusions:
1. max stack size seems to be different with and without local variable
2. max stack size seems to 
@abrahamjuliot Any ideas what `bytes = (sizeB * 8) / (sizeA - sizeB);` represents?

**Comment by abrahamjuliot** [comment]
Yeah, bytes just represent the difference.
