### ISSUE TITLE
dedicated server and cannot run your test

### ISSUE THREAD

**Issue by MikhailCarpov** [abrahamjuliot/creepjs#93]
Hi! I have a dedicated server and cannot run your test. What could be the problem? My config: i7-7700 core, video Graphics 630, 32 memory. WebGL 2/OpenGL ES 3.0 Chromium Available. win 16, chrome 87. What additional data do I need to add?
![Скриншот 2020-11-28 09 31 10](https://user-images.githubusercontent.com/66925827/100495488-5a33dd00-315d-11eb-9dff-158ba21b443b.png)

**Comment by abrahamjuliot** [comment]
This appears to be an unhandled error on my part. 🤔 

I pushed an update with passing console logs for each test. What do you see in the console now?

Here are the tests that should pass.

![image](https://user-images.githubusercontent.com/6946045/100497185-883e0080-310e-11eb-8142-d4e8dad2541b.png)

**Comment by MikhailCarpov** [comment]
result
![2020-11-28 11 55 58](https://user-images.githubusercontent.com/66925827/100498117-18149680-3171-11eb-958a-dc8e946fe677.png)

**Comment by abrahamjuliot** [comment]
So, I've narrowed it down to the webrtc test (media devices, worker, and webrtc should pass together before the final navigator test). By chance do you have anything on your network or settings that would affect webrtc? Does this error occur on the same device if you run it in Firefox? 

I attempted injecting custom errors in the webrtc test and was unable to reproduce this. I have a development site at https://creepjs--abrahamjuliot.repl.co. Right now, It's set to skip the webrtc test. If you run the tests there, does the issue persist?

**Comment by Thorin-Oakenpants** [comment]
OT: `nested iframe is valid up to nest 3` .. what happens in nest 4 (on FF)? My understanding is FF's limit is 10

**Comment by MikhailCarpov** [comment]
https://creepjs--abrahamjuliot.repl.co passed completely in chrome and firefox. It looks like a problem with webrtc, but I haven't been able to solve the problem yet.
![2020-11-28 13 49 51](https://user-images.githubusercontent.com/66925827/100514372-41d7b880-3185-11eb-87e5-682acc37286b.png)
![2020-11-28 13 50 46](https://user-images.githubusercontent.com/66925827/100514374-469c6c80-3185-11eb-9937-015c628c16fd.png)
![2020-11-28 13 51 43](https://user-images.githubusercontent.com/66925827/100514378-4b612080-3185-11eb-88ce-ef21d2dd8d80.png)
![2020-11-28 14 17 38](https://user-images.githubusercontent.com/66925827/100514380-51570180-3185-11eb-8705-142a3e1f2bd0.png)

**Comment by abrahamjuliot** [comment]
@MikhailCarpov I pushed an update to handle failed host lookups. This 701 error appears common and unresolved at `https://github.com/webrtc/samples/issues/1227`. I wonder if this is related to the DNS resolver. Do you encounter this issue if you switch to a secure DNS at chrome://settings/security?

**Comment by abrahamjuliot** [comment]
@Thorin-Oakenpants 

In #53, I'm using this [script](https://github.com/abrahamjuliot/creepjs/issues/53#issuecomment-716079533). In FF, after the 3rd iframe, the frame's window is undefined. Is 10 the tree node limit for iframes or an iframe nest limit regardless of teh number of tree nodes. Each iframe I test is nested in a div and there is a parent div nested within the template, so Iimagine I'm hitting ~10 tree nodes by the 3rd iframe.

**Comment by Thorin-Oakenpants** [comment]
ummm ... https://bugzilla.mozilla.org/show_bug.cgi?id=285395 probably 👍

**Comment by MikhailCarpov** [comment]
thanks for the fix
